version: '3'

services:
    mysql:
        container_name: mysql-source
        image: mysql
        ports: 
            - 3306:3306
        environment: 
            - MYSQL_DATABASE=schooldb
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=12345678


    postgres:
        container_name: postgresql-target
        image: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=schooldb
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=12345678
